[project]
name = "agentic-ai-starter"
version = "0.1.0"
description = "A from-scratch mini agent that plans, calls tools, and answers."
requires-python = ">=3.10"
dependencies = [
  "python-dotenv>=1.0.1",
  "openai>=1.40.0",
]

[tool.ruff]
line-length = 100
